参考: [100-Days-Of-ML-Code](https://github.com/Avik-Jain/100-Days-Of-ML-Code/blob/master/Code/Day3_Multiple_Linear_Regression.md)

## Concept

###  假设
1. 线性
2. 同方差性
3. 多变量正太分布性
4. 尽可能缺少特殊的变量

### Dummy variables 虚拟变量
- 将非数值型变量转换为数值变量

### Dummy variables trap 虚拟变量陷阱
- 虚拟变量陷阱是指如果一个变量可以由其他变量推断出来，然后去掉这个虚拟变量就行 m-1

## Step1 Data Preprocessing

### Importing the libraies

In [81]:
import pandas as pd
import numpy as np

### Import datasets

In [74]:
dataset = pd.read_csv('datasets/50_Startups.csv')
x = dataset.iloc[ : , : -1].values
y = dataset.iloc[ : , 4].values
print(dataset.loc[ : 5, : ])

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12


### Encoding Categorical data

In [75]:
x = x[ : , 1: ]# 应为第一列为虚拟变量陷阱列
print(x[ : 5, : ])  # 可以看出，第一列的数值没有了

[[136897.8 471784.1 'New York']
 [151377.59 443898.53 'California']
 [101145.55 407934.54 'Florida']
 [118671.85 383199.62 'New York']
 [91391.77 366168.42 'Florida']]


### Aviod Dummy Variable Trap

In [76]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder = LabelEncoder()
x[ : , 2] = label_encoder.fit_transform(x[ : , 2])
one_hot_encoder = OneHotEncoder(categorical_features=[2])
x = one_hot_encoder.fit_transform(x).toarray()
print(type(x))  # <class 'numpy.ndarray'>
print(x[ : 5, : ])

<class 'numpy.ndarray'>
[[0.0000000e+00 0.0000000e+00 1.0000000e+00 1.3689780e+05 4.7178410e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.5137759e+05 4.4389853e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.0114555e+05 4.0793454e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.1867185e+05 3.8319962e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 9.1391770e+04 3.6616842e+05]]


### Splitting the dataset into the Training set and Test set

In [77]:
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Step2 Fitting Multiple Linear Regression to the Training set

In [78]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

## Step3 Predicting the Test set result

In [80]:
y_pred = regressor.predict(x_test)
print(y_pred)

[106577.99626351 105343.13679758 102277.71300216  75479.98875116
 141370.81457967 155922.74625993  88638.20542025 102659.16409966
 125449.05313435 127073.25530139]
