参考: [100-Days-Of-ML-Code](https://github.com/Avik-Jain/100-Days-Of-ML-Code/blob/master/Code/Day%206%20Logistic%20Regression.md)

## Concept
1. logistic regression是一种分类算法
2. 利用sigmoid function应用, 并且与sigmoid的形状类似
3. logistic regression 相比于 linear regression 能处理离散分布问题

## Principle Concept
Todo

## Step 1 | Data Pre-Processing
### Importing the Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plot

### Importing the dataset

In [9]:
dataset = pd.read_csv('datasets/Social_Network_Ads.csv')
x = dataset.iloc[:, [2, 3]].values  # 我们只需要 age列 和 salary列即可 
y = dataset.iloc[:, 4].values
print(dataset.loc[ :5 , : ])

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0


### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

### Feature Scaling
- 因为有些分类方法随着数值大小而受影响，所以需要特征收敛到例如`[0, 1]`范围内

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
print(x_train[:5, :])

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]]


## Step 2 | Logistic Regression Model

### Fitting Logistic Regression to the Training set

In [18]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

### Predicting the Test set results

In [24]:
y_pre = classifier.predict(x_test)
print(y_pre[:10])
print(type(y_pre))

[0 0 0 0 0 0 0 1 0 1]
<class 'numpy.ndarray'>


## Step 3 | Evaluating The Predection

- 判断对错

### Making the Confusion Matrix

混淆矩阵，return 一个 n_class 列 n_class 行的矩阵，其中 `row[i]==col[i]`

所以根据上述原理，`num(class_1=class_1)=63`, `num(class_1=class_2)=5`,`num(class_2=class_1)=7`,`num(class_2=class_2)=25`

In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pre)
print(cm)
print(type(cm))

[[63  5]
 [ 7 25]]
<class 'numpy.ndarray'>


## Step 5 | Visualization

- todo